Computer_Institute/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from users import views as user_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path("course/",include("course.urls")),
    path("", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/",auth_views.LogoutView.as_view(template_name="users/logout.html"),name="logout"),
    path('register/',user_view.register,name="register"),
]

course/urls.py
from django.urls import path
from .views import *
urlpatterns=[
        path("",home,name="course-home"),
        path("new/",NewCourse.as_view(),name='course-new'),
        path("view/",ViewCourse.as_view(),name='course-view'),
        path("update/<int:pk>",UpdateCourse.as_view(),name="course-update"),
        path("delete/<int:pk>",DeleteCourse.as_view(),name="course-delete"),
        path("detail/<int:pk>",DetailCourse.as_view(),name="course-detail"),

]

course/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse

# Create your models here.
class course(models.Model):
    name=models.CharField(max_length=55)
    overview=models.TextField(blank=True,editable=True,null=True,verbose_name="Overview of Course :")
    description=models.TextField(blank=True,null=True)
    durations=models.IntegerField(validators=[MinValueValidator(0,"Durations should not be nagetive")],blank=True,null=True)
    fees=models.IntegerField(validators=[MinValueValidator(0,"Fees should not be Nagetive")])
    status=models.CharField(max_length=55,choices=[('Active','Active'),('Deactive','Deactive'),('Pending','Pending')])
    #user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='courses',null=True,blank=True)

    def __str__(self):
        return f" {self.name} "

    def get_absolute_url(self):
        return reverse('course-view')

users/models.py
from django.db import models
from django.contrib.auth.models import User
#from PIL import Image


# Create your models here.
# class profile(models.Model):
#     user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='profile')
#     image = models.ImageField(default='default.jpg',upload_to='profile_pics')
#
#
#     def __str__(self):
#         return f"{self.user.username} profile"
#
#     def save(self,*args,**kwargs):
#         super().save(*args,**kwargs)
#         img=Image.open(self.image.path)
#
#         if img.width>300 or img.height>300:
#             outputsize=(300,300)
#             img.thumbnail(outputsize)
#             img.save(self.image.path)
#
#         # adding date calender in createview plase put this code in createview
#         # from django.forms.extras.widgets import SelectDateWidget
#         # form = super(EnvironmentCreateView, self).get_form()
#         # form.fields['creation_date'].widget = SelectDateWidget()
#         # return form

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout,Div
#from .models import profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(widget=(forms.TextInput(attrs={'placeholder':'Email'})))
    username= forms.CharField(widget=(forms.TextInput(attrs={'placeholder':'Username'})))
    password1 = forms.CharField(widget=forms.PasswordInput({'placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput({'placeholder': ' Retype Password'}))

    class Meta:
        model=User
        fields=['username','email','password1','password2']

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False
        self.helper.layout=Layout(
            Div('username',css_class='input-group mb-3')
        )


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email','first_name','last_name']


# class ProfileUpdateForm(forms.ModelForm):
#     class Meta:
#         model = profile
#         fields = ['image']

course/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,"course/home.html")


from django.views.generic import CreateView,ListView,UpdateView,DeleteView,DetailView
from .models import course
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse

# Cr̥eate your views here.
class NewCourse(SuccessMessageMixin,CreateView):
    model = course
    fields = '__all__'
    success_message = "%(name)s is created"

class ViewCourse(ListView):
    model = course
    context_object_name = 'courses'

class UpdateCourse(SuccessMessageMixin,UpdateView):
    model = course
    fields = '__all__'
    success_message = "%(name)s is Updated"

class DeleteCourse(DeleteView):
    model = course
    success_url = '/course/view'
    success_message = "course was deleted successfully."

    def delete(self, request, *args, **kwargs):
        #messages.error(self.request, self.success_message)
        messages.success(self.request, self.success_message)
        return super(DeleteCourse, self).delete(request, *args, **kwargs)

class DetailCourse(DetailView):
    model = course

def get_fees(request, course_id):
        courses = course.objects.get(pk=course_id);
        return JsonResponse({'fees': courses.fees});

users/views.py
from django.shortcuts import render,redirect
from .forms import UserRegisterForm,UserUpdateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.db.models.functions import TruncMonth
from django.http.response import JsonResponse

# Create your views here.
def register(request):
    if request.method=='POST':
        form = UserRegisterForm(request.POST)
        print("method post")
        if form.is_valid():
            form.save()
            print("data is saved")
            username=form.cleaned_data["username"]
            messages.success(request,f"account is created for {username} you can now login ")
            return redirect('login')
    else:
        form=UserRegisterForm()
    return render(request,"users/register.html",{
        "form":form
    })


#@login_required(login_url='login')
# def profile(request):
#     if request.method == 'POST' :
#         u_form = UserUpdateForm(request.POST,instance=request.user)
#         p_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
#         if u_form.is_valid() and p_form.is_valid():
#             u_form.save()
#             p_form.save()
#             messages.success(request, f" profile is updated  ")
#             return redirect('profile')
#         else:
#             return render(request, "users/profile.html", {
#                 "u_form": u_form,
#                 "p_form": p_form
#             })
#
#     u_form=UserUpdateForm(instance=request.user)
#     p_form=ProfileUpdateForm(instance=request.user.profile)
#     return render(request, "users/profile.html", {
#         "u_form":u_form,
#         "p_form":p_form
#     })

templates/blank.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <title>
   {% block title  %}    AdminLTE 3 | Blank Page {% endblock %}
  </title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %} ">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %} ">
  {%  block extra_css %}
 {% endblock %}

</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="" class="nav-link">Home</a>
      </li>

    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">

       <li class="nav-item">
           <form action="{% url 'logout' %}" method="post">
               {% csrf_token %}
               <input type="submit" class="btn btn-secondary" value="logout">
           </form>
      </li>


      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>

    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="" class="brand-link">
{#      <img src="" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">#}
      <span class="brand-text font-weight-light">Arham Institute</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">



      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

        {#   course Menu#}
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-school"></i>
              <p>
                Course
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'course-new' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Entry</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'course-view' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View</p>
                </a>
              </li>

            </ul>
          </li>
        {#   Student Menu#}
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Student
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Entry</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View</p>
                </a>
              </li>

            </ul>
          </li>
        {#   Addmission Menu#}
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Addmission
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Entry</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View</p>
                </a>
              </li>

            </ul>
          </li>
        {#   Payment Menu#}
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                  Payment
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Entry</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>View</p>
                </a>
              </li>

            </ul>
          </li>




        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            {% block page_heading %} <h1>Blank Page</h1> {% endblock %}
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Blank Page</li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Title</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
            {% block body %}
                Start creating your amazing application!
            {% endblock %}
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
          Footer
        </div>
        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; 2024-2025 <a href="">Arham Computer Institute</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js'%} "></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
{% block extra_js %}
{% endblock %}

</body>
</html>

templates/course/course_confirm_delete.html
{% extends "blank.html" %}
{% load static  %}
{% load crispy_forms_field %}
{% block page_heading %}
  <h1>  {{ object.name }} Delete Page  </h1>
{% endblock %}
{% block extra_css %}
{% endblock %}

{% block body %}
    <form method="post">
    {% csrf_token %}
    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card card-danger">
        <div class="card-header">
          <h3 class="card-title card-danger" >Are you sure you want to delete ?</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
              <div class="row">
                <div class="col-12 col-sm-4">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">Duration</span>
                      <span class="info-box-number text-center text-muted mb-0">{{ object.durations }} Months</span>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-sm-4">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">Fees </span>
                      <span class="info-box-number text-center text-muted mb-0">{{ object.fees }}</span>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-sm-4">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">Status</span>
                      <span class="info-box-number text-center text-muted mb-0">{{ object.status }}</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <h4>Description </h4>
                    <div class="post">

                      {{ object.description | safe }}
                    </div>


                </div>
              </div>
            </div>
            <div class="col-12 col-md-12 col-lg-4 order-1 order-md-2">
              <h3 class="text-primary"><i class="fas fa-paint-brush"></i> Overview </h3>
              <p class="text-muted">
                {{ object.overview | safe }}
              </p>
              <br>
              <div class="text-muted">
                <p class="text-sm">Created By
                  <b class="d-block">{{ object.user.username }}</b>
                </p>

              </div>


              </div>
            </div>
          </div>
        </div>
        <!-- /.card-body -->
        <input type="submit" class="btn btn-lg btn-danger" value="Yes,I am sure Delete">
        <a href="{% url 'course-view' %}" class="btn btn-info btn-lg" > cancel </a>
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
    </form>


{% endblock %}
{% block extra_js %}
{% endblock %}

templates/course/course_detail.html
{% extends "blank.html" %}
{% load static  %}
{% load crispy_forms_field %}
{% block page_heading %}
  <h1>  {{ object.name }}  </h1>
{% endblock %}
{% block extra_css %}
{% endblock %}

{% block body %}

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Course Detail</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
              <i class="fas fa-times"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-8 order-2 order-md-1">
              <div class="row">
                <div class="col-12 col-sm-4">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">Duration</span>
                      <span class="info-box-number text-center text-muted mb-0">{{ object.durations }} Months</span>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-sm-4">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">Fees </span>
                      <span class="info-box-number text-center text-muted mb-0">{{ object.fees }}</span>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-sm-4">
                  <div class="info-box bg-light">
                    <div class="info-box-content">
                      <span class="info-box-text text-center text-muted">Status</span>
                      <span class="info-box-number text-center text-muted mb-0">{{ object.status }}</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-12">
                  <h4>Description </h4>
                    <div class="post">

                      {{ object.description | safe }}
                    </div>


                </div>
              </div>
            </div>
            <div class="col-12 col-md-12 col-lg-4 order-1 order-md-2">
              <h3 class="text-primary"><i class="fas fa-paint-brush"></i> Overview </h3>
              <p class="text-muted">
                {{ object.overview | safe }}
              </p>
              <br>
              <div class="text-muted">
                <p class="text-sm">Created By
                  <b class="d-block">{{ object.user.username }}</b>
                </p>

              </div>


              </div>
            </div>
          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->



{% endblock %}
{% block extra_js %}
{% endblock %}

templates/course/course_form.html
{% extends "blank.html" %}
{% load static  %}
{% load crispy_forms_field %}
{% block page_heading %}
  <h1>  Course Entry Form </h1>
{% endblock %}


{% block extra_css %}
 <!-- summernote -->
  <link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">
{% endblock %}
{% block body %}


    <!-- Main content -->


        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- jquery validation -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">New Course Form </h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form id="quickForm" novalidate="novalidate" method="post">
                  {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label >Name </label>

                    {% crispy_field form.name 'class' 'form-control' %}
                     {% if form.name.errors %}
                         {% for error in form.name.errors %}
                             <label class="error"><b>{{ error }}</b></label>
                         {% endfor %}
                     {% endif %}
                  </div>
                  <div class="form-group">
                    <label >Overview</label>
                    {% crispy_field form.overview  %}
                    {% if form.overview.errors %}
                         {% for error in form.overview.errors %}
                             <label class="error"><b>{{ error }}</b></label>
                         {% endfor %}
                     {% endif %}
                  </div>

                  <div class="form-group">
                    <label >Description :</label>
                    {% crispy_field form.description %}

                     {% if form.description.errors %}
                         {% for error in form.desciption.errors %}
                             <label class="error"><b>{{ error }}</b></label>
                         {% endfor %}
                     {% endif %}
                  </div>
                  <div class="row">
                      <div class="form-group col-lg-4 col-sm-12">
                    <label >Durations  (in Months) :</label>
                    {% crispy_field form.durations 'class' 'form-control' %}
                    {% if form.durations.errors %}
                         {% for error in form.durations.errors %}
                             <label class="error"><b>{{ error }}</b></label>
                         {% endfor %}
                     {% endif %}
                  </div>
                      <div class="form-group col-lg-4 col-sm-12">
                    <label>Fees :</label>
                    {% crispy_field form.fees 'class' 'form-control' %}
                    {% if form.fees.errors %}
                         {% for error in form.fees.errors %}
                             <label class="error"><b>{{ error }}</b></label>
                         {% endfor %}
                     {% endif %}
                  </div>
                      <div class="form-group col-lg-4 col-sm-12">
                    <label>Status :</label>
                    {% crispy_field form.status 'class' 'form-control' %}
                    {% if form.status.errors %}
                         {% for error in form.status.errors %}
                             <label class="error"><b>{{ error }}</b></label>
                         {% endfor %}
                     {% endif %}
                </div>
{#                   <div class="form-group col-lg-3 col-sm-12">#}
{#                    <label>User :</label>#}
{#                    {% crispy_field form.user %}#}
{#                    {% if form.user.errors %}#}
{#                         {% for error in form.user.errors %}#}
{#                             <label class="error"><b>{{ error }}</b></label>#}
{#                         {% endfor %}#}
{#                     {% endif %}#}
{#                </div>#}
                  </div>

                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->
            </div>
          <!--/.col (left) -->
          <!-- right column -->
          <div class="col-md-6">

          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->

{% endblock %}
{% block extra_js %}

    <!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js'%}"></script>


<script>
  $(function () {
    // Summernote
    $('#id_overview').summernote()
    $('#id_description').summernote()

    // phone input mask
    //Money Euro
    $('[data-mask]').inputmask()

  })
</script>


{% endblock %}

templates/course/course_list.html
{% extends "blank.html" %}
{% load static %}
{% block extra_css %}
   {% include "course/datatable_css2.html" %}
{% endblock %}
{% block body %}
     <div class="card">
              <div class="card-header">
                <h3 class="card-title">Course List  </h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="example3" class="table table-bordered table-striped display nowrap" style="width: 100%">
                  <thead>
                  <tr>
                    <th>Name</th>
                    <th>Overview</th>
                    <th>Durations</th>
                    <th>Fees</th>
                    <th>status</th>
                    <th> Action</th>
                  </tr>
                  </thead>
                  <tbody>
                    {% for course in courses %}
                        <tr>
                            <td>{{ course.name }}</td>
                            <td>{{ course.overview | safe }}</td>
                            <td>{{ course.durations }}</td>
                            <td>{{ course.fees }}</td>
                            <td>{{ course.status }}</td>
                            <td><a class="btn btn-info btn-sm" href="{% url 'course-update' course.id %}">
                                <i class="fas fa-pencil-alt">
                              </i>
                                edit</a>
                                <a class="btn btn-primary btn-sm" href="{% url 'course-detail' course.id %}">
                                <i class="fas fa-folder">
                              </i>
                                details </a>
                                <a class="btn btn-danger btn-sm" href="{% url 'course-delete' course.id %}">
                                <i class="fas fa-trash">
                              </i>
                                delete </a>
                            </td>
                        </tr>
                    {% endfor %}
                  </tbody>
                  <tfoot>
                  <tr>
                    <th>Name</th>
                    <th>Overview</th>
                    <th>Durations</th>
                    <th>Fees</th>
                    <th>status</th>
                    <th> Action</th>
                  </tr>
                  </tfoot>
                </table>
              </div>
              <!-- /.card-body -->
            </div>

{% endblock %}
{% block extra_js %}
    <!-- DataTables  & Plugins -->
 {% include "course/datatable_script2.html" %}
{% endblock %}

templates/course/home.html
{% extends "blank.html" %}

{% block title %}
  Coure Home
{% endblock %}

{% block page_heading %}
  Course Page
{% endblock %}

{% block body %}

<h1> Course Home page </h1>

{%  endblock %}

templates/users/body_end_script.html
{% load static  %}
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- SweetAlert2 -->
<script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>

templates/users/css_head_files.html
{% load static %}
<!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{%  static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
    <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
 <!-- SweetAlert2 -->
  <link rel="stylesheet" href="{% static 'plugins/sweetalert2-theme-bootstrap-4/bootstrap-4.min.css' %}">